# Generated by Django 2.1.4 on 2020-03-12 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=8)),
                ('sex', models.CharField(max_length=2)),
                ('age', models.CharField(max_length=2)),
                ('pswd', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=8)),
                ('department', models.CharField(max_length=10)),
                ('sex', models.CharField(max_length=2)),
                ('age', models.CharField(max_length=2)),
                ('pswd', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=8)),
                ('department', models.CharField(max_length=10)),
                ('sex', models.CharField(max_length=2)),
                ('age', models.CharField(max_length=2)),
                ('pswd', models.CharField(max_length=8)),
            ],
        ),
    ]
