# Generated by Django 2.1.4 on 2020-03-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwc', '0002_auto_20200312_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('number', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=8)),
                ('department', models.CharField(max_length=10)),
                ('usertype', models.CharField(max_length=10)),
                ('sex', models.CharField(max_length=2)),
                ('age', models.CharField(max_length=2)),
                ('pswd', models.CharField(max_length=8)),
            ],
        ),
        migrations.DeleteModel(
            name='manager',
        ),
        migrations.DeleteModel(
            name='student',
        ),
        migrations.DeleteModel(
            name='teacher',
        ),
    ]
