# Generated by Django 2.1.4 on 2020-03-15 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwc', '0004_courseinfo_term'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseinfo',
            name='course_number',
        ),
    ]
