# Generated by Django 2.1.4 on 2020-03-15 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwc', '0005_remove_courseinfo_course_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinfo',
            name='student_score',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
