# Generated by Django 2.1.4 on 2020-03-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwc', '0007_opened_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='opened_course',
            name='teacher_number',
            field=models.CharField(default=200, max_length=8),
            preserve_default=False,
        ),
    ]
