# Generated by Django 2.1.4 on 2020-03-16 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwc', '0008_opened_course_teacher_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseinfo',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='course_id',
            field=models.CharField(max_length=8),
        ),
    ]
