# Generated by Django 2.1.4 on 2020-03-16 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwc', '0010_auto_20200316_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinfo',
            name='course_id',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='id',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
