# Generated by Django 2.1.4 on 2020-03-16 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwc', '0011_auto_20200316_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinfo',
            name='course_id',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
