# Generated by Django 2.1.4 on 2020-03-16 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwc', '0012_auto_20200316_0845'),
    ]

    operations = [
        migrations.DeleteModel(
            name='courseinfo',
        ),
    ]
