# Generated by Django 2.1.4 on 2020-03-16 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwc', '0013_delete_courseinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='courseinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=8)),
                ('course_name', models.CharField(max_length=15)),
                ('course_credit', models.CharField(max_length=2)),
                ('course_status', models.CharField(max_length=8)),
                ('teacher_number', models.CharField(max_length=8)),
                ('teacher_name', models.CharField(max_length=8)),
                ('student_number', models.CharField(max_length=8)),
                ('student_name', models.CharField(max_length=8)),
                ('student_score', models.CharField(max_length=3, null=True)),
            ],
        ),
    ]
