# Generated by Django 2.1.4 on 2020-03-16 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwc', '0018_courseinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='courseinfo',
        ),
    ]
