# Generated by Django 3.0.5 on 2020-07-19 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Platform', '0002_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='oTime',
            field=models.CharField(max_length=30),
        ),
    ]
