# Generated by Django 3.0.5 on 2020-07-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Platform', '0004_restaurant_remail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='dysy',
            field=models.IntegerField(default=0),
        ),
    ]
