# Generated by Django 3.0.5 on 2020-07-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Platform', '0005_auto_20200721_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='TmpRestaurant',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('t_name', models.CharField(max_length=15)),
                ('t_addr', models.CharField(max_length=2)),
                ('t_tel', models.CharField(max_length=15)),
                ('t_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='rEmail',
            field=models.EmailField(max_length=254),
        ),
    ]
