# Generated by Django 3.0.5 on 2020-07-21 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Platform', '0006_auto_20200722_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmprestaurant',
            name='t_status',
            field=models.IntegerField(default=1),
        ),
    ]
