# Generated by Django 2.1.4 on 2020-07-25 01:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Platform', '0008_order_evaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='infor',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='picture',
            field=models.CharField(default=1, max_length=9),
            preserve_default=False,
        ),
    ]
