# Generated by Django 2.1.4 on 2020-07-25 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Platform', '0009_auto_20200725_0923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='picture',
        ),
        migrations.AddField(
            model_name='menu',
            name='image',
            field=models.ImageField(default=2, upload_to=''),
            preserve_default=False,
        ),
    ]
