# Generated by Django 2.1.4 on 2020-08-06 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Platform', '0011_tmp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('start', models.CharField(max_length=15)),
                ('end', models.CharField(max_length=15)),
                ('discount', models.IntegerField()),
                ('restaurantId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Platform.Restaurant')),
            ],
        ),
        migrations.DeleteModel(
            name='Tmp',
        ),
    ]
