# Generated by Django 2.1.4 on 2020-08-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Platform', '0012_auto_20200806_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.ImageField(upload_to='image'),
        ),
    ]
