# Generated by Django 2.1.4 on 2020-08-07 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Platform', '0013_auto_20200806_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(default=1, upload_to='image'),
            preserve_default=False,
        ),
    ]
