# Generated by Django 2.1.4 on 2020-08-07 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Platform', '0015_auto_20200807_0943'),
    ]

    operations = [
        migrations.DeleteModel(
            name='orderId',
        ),
        migrations.RemoveField(
            model_name='order',
            name='realId',
        ),
    ]
